### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-containerize#9]
I don't feel this provide a lot more than https://openliberty.io/guides/docker.html
How about adding the following:

- Explain the docker layer system: read only, layer on top another one
when you do docker build, what happens? e.g. layering the images
explain how docker run works?

- add docker hub bit and talk a bit docker push and docker pull from a project docker registry or personal docker registry

- add some useful command to find out what's happening in the container
docker logs <container_id>
docker stats <container_id>

By the way, in the previous guide, you use COPY while this guide uses ADD. It might be good to explain that ADD copies the file and also extract the file.

**Comment by yeekangc** [comment]
@justineechen @gkwan-ibm ^^^

**Comment by Emily-Jiang** [comment]
After reviewing it again, I think in order not to cause more confusion, I suggest to add the explanation of Dockerfile in the original [guide](https://openliberty.io/guides/docker.html#testing-the-container) to address the [issue](https://github.com/OpenLiberty/guides-common/issues/242). I would focus on creating a guide on how to use Operator rather than creating another docker guide with 99% repeating the previous guide.

**Comment by yeekangc** [comment]
This guide shouldn't conflict with the current guide out there.  The former focuses on how you containerize your app/service while the latter (current one out there) talks about iteratively developing with runtime inside containers.

We have a separate issue for operators in the backlog.

**Comment by Emily-Jiang** [comment]
what is the guide trying to do?

**Comment by yeekangc** [comment]
I presume you meant this new guide here, @Emily-Jiang?  It's meant to cover how you can take your service/app, create a Dockerfile, build an image and run it inside a container.

It's also meant to complete the series going from Containerize to Kubernetes.

The other guide doesn't talk about what's in the Dockerfile as much and focuses on how you can map your container to your code (loose app) and do iterative development.

**Comment by Emily-Jiang** [comment]
I don't think there are a lot of difference between these two guides. You can do a compare to list the difference. I still think consolidating the info is better than multiple guides on docker.

**Comment by yeekangc** [comment]
We are making updates -- see https://github.com/OpenLiberty/guide-docker/pull/50 -- to clarify the focus of the current guide.

I can understand your point, @Emily-Jiang.  Some concepts may overlap but they are meant to serve different purposes.

We will proceed to proceed to publish the new Containerize guide.  We can then see where we shall go from there.

Open to retire the current guide should we can consolidate what it has at an appropriate place.

**Comment by gkwan-ibm** [comment]
Both guides content are different, see the following table. The original Docker guide is not to containerize application. The main difference is the second last row.

**Section** | **Original Docker Guide** | **New Containerizing Guide**
----------- | ------------------------- | ----------------------------
**What you’ll learn** | Explain "What is Docker?", "What is a container?", and "Why use containers?" | ---
**Building your application** | simple mvn install | Specifically, ask reader to package the microservice in an archive form and to try it out
**Creating the Dockerfile** | The Dockerfile is different and the description is different. The Docker is not package the application into an image. Also, explain " .dockerignore" | Explain to use `ADD` command to package the microservice.
**Building your Docker image** | More explanation for build ID and option `--no-cache=true` | partial content as the original Docker guide
*Run Docker image* | The section title is "Containerize your application". It may need to be updated. Explain how to run the local application through the docker image. | Explain how to run the 2 microservices and determine the ip so that inventory service can invoke system service
**Testing the container** | Describe to try out the app | The section title is different. It is "Testing the microservices". Run unit tests.
